### ISSUE TITLE
How to use this to create qt widget?

### ISSUE THREAD

**Issue by Akimotorakiyu** [node-3d/deps-qt-gui-raub#2]
How to use this to create qt widget?

**Comment by raub** [comment]
Hello. This is a dependency package, that only distributes the Qt binaries for Windows, Linux and OSX via NPM. Please see https://github.com/node-3d/3d-qml-raub and its examples for QML usage. (there is likely an issue with OSX distribution though)

If you are not interested in QML you may use this package as-is: it will install you a bunch of DLLs (SO, etc, depending on the platform). And there you have it, you may go on building an addon for Node.js which somehow uses those Qt binaries. This is exactly what is done here:

- https://github.com/node-3d/deps-qmlui-raub - this one is built with Qt, resulting in a DLL of its own, and
- https://github.com/node-3d/3d-qml-raub - this one uses the former wrapping it into a Node.js addon

**Comment by Akimotorakiyu** [comment]
@raub Thank you!
